version: '1.0'

cms:
    type: GraphCMS
    host: API_URL
    privateKey: "your key"

backups:
    schemaPath: ./backups/schema
    contentPath: ./backups/content
    schemas:
        - Author
        - Blog
