version: '1.0'

cms:
    provider: GraphCMS
    host: API_URL
    privateKey: "your key"

backups:
    schemaPath: ./backups/schema
    contentPath: ./backups/content
    schemas:
        - Author
        - Blog

API_URL: "Booyah"
