version: '1.0'

cms:
    provider: GraphCMS

backups:
    path: /Users/arroyo/.cmsutil/backups
    stage: "master"
    enumerations:
        - Category
        - Tags

CMS_API_URL: "Set your CMS API URL here or use envar CMS_API_URL on host"
CMS_API_KEY: "Set your CMS API Key here or use envar CMS_API_KEY on host"