version: 3.8

services:
    cli:
        name: grutil
        # image: arroyo/grutil
        build:
            context: ./docker
        environment:
            CMS_API_URL:
            CMS_API_KEY:
        entrypoint: 
            - '/bin/ash'
