version: '3.8'

services:
    cli:
        container_name: mygrutil
        build:
            context: ./docker
        environment:
            CMS_API_URL:
            CMS_API_KEY:
        entrypoint: 
            - 'tail'
            - '-f'
            - '/dev/null'
